language: java
jdk:
  - oraclejdk8
 
before_install:
 - chmod +x gradlew

install: ./gradlew checkSnapshotDependencies compileJava
script: ./gradlew check jacocoTestReport javadoc

after_failure:
- cat build/test-results/test/*.xml
